apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KC_DB_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= # base64 encoded 'admin'